---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgARYH7guh2Y6RCRXaKTgdR4T3BBPGCAzzTvbmWN/VjRaoFhH8X7kURr00/oXo51VaTPbhJiQCH9glrhX+cHZiGfhdUGp6ljRlnJlBozRDJJu5H+ERg1+BbIJwDQmbzbNZyttTJiiGL/NLJmmGcyJlMyofUfeZNvKxXqzUEkaP/yc0JcFHXiPHLCg5OyBszdxawQo9fyOBtzdtTO+D2PQ6mRYtkGDr92uVmhOSAgexdqv2Zo6vdIAN7UgEYELEEpGWB97HebcSUwMkySD7TdojPRcD2BBcYM4q1/HESWbtAmZb/cJVNupUTE30IS7YxYP/GytZIf9aNvOhjOI1SVBWnMDu+hQSkByWGVwj/inlx52LbjL3MRqDZAqmx80pMd5ebn1xgKCX+6D07LyXqDzE3cOSWBHEgNGIWxFLKXhbOAnol2a/hJjj14qY/7Mn/5ZQZO8YhSWXe2jmq/U/6V7LKsP9GawgR2J6ZpDepgEVoSM1lRuiGqgu65BDx+SxvWEFMaxM7dZX7GJgABgxocvwTsJg1bWMQyqvbDNCKoAt2qXyUiACGL6WvCQfwe9L7DFn2qTzkoheOkFzJ96mu+YzjpMqqk0GN+aF/6X72/kqTpGdlpbx+AV6I2LIF7/wrDWoLoQ0xBt10ed3H1eQVKnbfWw6dQJ2VI3AV9Yfl/U5vNf95tdETXevCJxKeLa61glu/InadMUoRtCQnwUaP+9L1sMXqBfZM6j3SxeF5he3Q9svMsidF2jQ4ri/LpylPTCERCVHo4zMjQyANlVgVW4t1Xw3oDhfeLvPGOzlufPTLhAL4IkA7j9AltRtq818gmVkfoF7dOm948qge8lHrJUgjnipfUOBNEkL0BQWOCWpcVXrgRqch322yqHrkWkBSr19VOvRqa2d0st5T3N/2uAVyE4w==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
